-- VoiceGuard: run this once in your own Supabase project's SQL editor
create extension if not exists pgcrypto with schema extensions;
create type public.app_role as enum ('admin','moderator','user');
create table public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  role app_role not null,
  unique (user_id, role)
);
grant select on public.user_roles to authenticated;
grant all on public.user_roles to service_role;
alter table public.user_roles enable row level security;
create or replace function public.has_role(_user_id uuid, _role app_role)
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.user_roles where user_id=_user_id and role=_role) $$;
create policy "own roles readable" on public.user_roles for select to authenticated using (user_id = auth.uid());

-- first user to sign up becomes admin
create or replace function public.handle_first_admin()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from public.user_roles where role='admin') then
    insert into public.user_roles(user_id, role) values (new.id, 'admin');
  end if;
  return new;
end $$;
create trigger on_auth_user_created_admin after insert on auth.users
for each row execute function public.handle_first_admin();

create table public.bot_settings (
  id int primary key default 1 check (id = 1),
  voice_channel_ids text[] not null default '{}',
  text_channel_ids text[] not null default '{}',
  text_all_channels boolean not null default false,
  log_channel_id text not null default '',
  alert_channel_id text not null default '',
  alert_role_id text not null default '',
  ignored_user_ids text[] not null default '{}',
  ignored_role_ids text[] not null default '{}',
  warning_expiry_days int not null default 30,
  sexual_instant_ban boolean not null default true,
  fuzzy_matching boolean not null default true,
  ladder jsonb not null default '[{"from":1,"action":"warn","duration":0},{"from":4,"action":"timeout","duration":600},{"from":6,"action":"timeout","duration":3600},{"from":8,"action":"ban","duration":0}]',
  category_weights jsonb not null default '{"mild":1,"abuse":2,"severe":3}',
  bot_api_key text not null default encode(extensions.gen_random_bytes(24),'hex'),
  discord_token text not null default '',
  deepgram_keys text[] not null default '{}',
  server_words text[] not null default '{VC,Gangster MC}',
  min_confidence real not null default 0.85 check (min_confidence between 0 and 1),
  min_confidence_short real not null default 0.92 check (min_confidence_short between 0 and 1),
  ai_enabled boolean not null default false,
  ai_provider text not null default 'openai_compatible' check (ai_provider in ('openai_compatible','anthropic')),
  ai_base_url text not null default '',
  ai_model text not null default '',
  ai_api_key text not null default '',
  command_channel_id text not null default '',
  command_allowed_user_ids text[] not null default '{}',
  command_allowed_role_ids text[] not null default '{}',
  bot_last_seen timestamptz,
  bot_status jsonb not null default '{}',
  updated_at timestamptz not null default now()
);
insert into public.bot_settings (id) values (1);
grant select, update on public.bot_settings to authenticated;
grant all on public.bot_settings to service_role;
alter table public.bot_settings enable row level security;
create policy "admins read settings" on public.bot_settings for select to authenticated using (public.has_role(auth.uid(),'admin'));
create policy "admins update settings" on public.bot_settings for update to authenticated using (public.has_role(auth.uid(),'admin'));

create table public.slang_words (
  id uuid primary key default gen_random_uuid(),
  category text not null check (category in ('mild','abuse','severe','sexual','provoking','allow')),
  word text not null,
  language text not null default 'hindi',
  created_at timestamptz not null default now(),
  unique (category, word)
);
grant select, insert, update, delete on public.slang_words to authenticated;
grant all on public.slang_words to service_role;
alter table public.slang_words enable row level security;
create policy "admins manage words" on public.slang_words for all to authenticated using (public.has_role(auth.uid(),'admin')) with check (public.has_role(auth.uid(),'admin'));

create table public.infractions (
  id uuid primary key default gen_random_uuid(),
  discord_user_id text not null,
  username text not null default '',
  channel_name text not null default '',
  category text not null,
  matched text not null default '',
  transcript text not null default '',
  action text not null,
  duration_seconds int not null default 0,
  points int not null default 0,
  cleared boolean not null default false,
  created_at timestamptz not null default now()
);
create index on public.infractions (discord_user_id, created_at desc);
grant select, update, delete on public.infractions to authenticated;
grant all on public.infractions to service_role;
alter table public.infractions enable row level security;
create policy "admins read infractions" on public.infractions for select to authenticated using (public.has_role(auth.uid(),'admin'));
create policy "admins update infractions" on public.infractions for update to authenticated using (public.has_role(auth.uid(),'admin'));
create policy "admins delete infractions" on public.infractions for delete to authenticated using (public.has_role(auth.uid(),'admin'));

create table public.ai_decision_logs (
  id uuid primary key default gen_random_uuid(),
  transcript text not null default '',
  matched text not null default '',
  keyword text not null default '',
  category text not null default '',
  source text not null default 'text' check (source in ('voice','text')),
  verdict text not null check (verdict in ('violation','safe','uncertain')),
  reason text not null default '',
  provider text not null default '',
  model text not null default '',
  outcome text not null default '' check (outcome in ('punishment_continued','ignored','moderator_review','connection_test')),
  is_test boolean not null default false,
  discord_user_id text not null default '',
  username text not null default '',
  channel_id text not null default '',
  channel_name text not null default '',
  created_at timestamptz not null default now()
);
grant select on public.ai_decision_logs to authenticated;
grant all on public.ai_decision_logs to service_role;
alter table public.ai_decision_logs enable row level security;
create policy "admins read ai decision logs" on public.ai_decision_logs for select to authenticated using (public.has_role(auth.uid(),'admin'));
create index ai_decision_logs_created_at_idx on public.ai_decision_logs (created_at desc);
create index ai_decision_logs_verdict_idx on public.ai_decision_logs (verdict, created_at desc);
create index ai_decision_logs_discord_user_idx on public.ai_decision_logs (discord_user_id, created_at desc);

insert into public.slang_words (category, word, language) values
('mild','chutiya','hindi'),('mild','kamina','hindi'),('mild','harami','hindi'),('mild','kutta','hindi'),('mild','gandu','hindi'),('mild','nalayak','hindi'),('mild','idiot','english'),('mild','stupid','english'),
('abuse','madarchod','hindi'),('abuse','mc','hindi'),('abuse','behenchod','hindi'),('abuse','bc','hindi'),('abuse','bhosdike','hindi'),('abuse','bhopadike','hindi'),('abuse','lavde','hindi'),('abuse','lauda','hindi'),('abuse','lund','hindi'),('abuse','fuck','english'),('abuse','motherfucker','english'),('abuse','bitch','english'),('abuse','asshole','english'),
('severe','teri maa ki','hindi'),('severe','teri mummy ki','hindi'),('severe','teri behen ki','hindi'),('severe','teri maa ko','hindi'),('severe','teri mummy ko','hindi'),('severe','maa chod','hindi'),('severe','randi','hindi'),('severe','randi ka','hindi'),
('sexual','nude bhej','hindi'),('sexual','send nudes','english'),('sexual','rape','english'),('sexual','rape kar','hindi'),('sexual','chodunga','hindi'),('sexual','sexy photo','english'),
('provoking','himmat hai to','hindi'),('provoking','aaja bahar','hindi'),('provoking','dekh lunga','hindi'),('provoking','come at me','english'),
('allow','abc','english'),('allow','bcci','english'),('allow','mcdonalds','english'),('allow','mcq','english');insert into public.slang_words (category, word, language) values
('severe','teri mammi ki','hindi'),('severe','teri ma ki','hindi'),('severe','teri amma ki','hindi'),('severe','teri maa ka','hindi'),('severe','teri bahen ki','hindi'),('severe','maa ki chut','hindi'),('severe','behen ki chut','hindi'),
('abuse','bhosadike','hindi'),('abuse','bhosdi ke','hindi'),('abuse','bhosdiwale','hindi'),('abuse','bhenchod','hindi'),('abuse','bahenchod','hindi'),('abuse','madharchod','hindi'),('abuse','lodu','hindi'),('abuse','chod','hindi'),('abuse','gaand','hindi'),('abuse','randwa','hindi'),
('mild','chutiye','hindi'),('mild','haramzada','hindi'),('mild','kamine','hindi'),('mild','kutiya','hindi'),('mild','suar','hindi'),
('provoking','bahar mil','hindi'),('provoking','teri aukat','hindi'),('provoking','aukat dikha','hindi')
on conflict (category, word) do nothing;

insert into public.slang_words(category,word,language) values
('allow','cutie','english'),
('allow','cute','english'),
('allow','vc','english'),
('allow','gangster mc','english'),
('allow','gangstar mc','english'),
('allow','to','english'),
('allow','toh','hindi'),
('allow','tt','english')
on conflict (category, word) do nothing;
insert into public.slang_words(category,word,language) values
('abuse','arsehole','english'),
('abuse','ass hole','english'),
('abuse','asshole','english'),
('abuse','bainchod','bengali'),
('abuse','bakchod','hindi'),
('abuse','bakchodi','hindi'),
('abuse','bc','hindi'),
('abuse','bc mc','hindi'),
('abuse','bevarsi','kannada'),
('abuse','bewakoof gandu','hindi'),
('abuse','bewaqoof','urdu'),
('abuse','bhadva','hindi'),
('abuse','bhadvo','gujarati'),
('abuse','bhadvya','marathi'),
('abuse','bhadwa','hindi'),
('abuse','bhadwa','urdu'),
('abuse','bhadwe','hindi'),
('abuse','bhen da','punjabi'),
('abuse','bhenkelode','hindi'),
('abuse','bhikarchot','marathi'),
('abuse','bhoothni','punjabi'),
('abuse','bhootni ke','punjabi'),
('abuse','bhosda','hindi'),
('abuse','bhosdina','gujarati'),
('abuse','bitch','english'),
('abuse','bitches','english'),
('abuse','bkl','hindi'),
('abuse','bloody bastard','english'),
('abuse','boka choda','bengali'),
('abuse','bokachoda','bengali'),
('abuse','bokachodi','bengali'),
('abuse','bsdk','hindi'),
('abuse','bullshit','english'),
('abuse','bund','punjabi'),
('abuse','bund mara','punjabi'),
('abuse','chakka','hindi'),
('abuse','chapri','hindi'),
('abuse','chavla','punjabi'),
('abuse','chhapri','hindi'),
('abuse','chinal','marathi'),
('abuse','chodu','bengali'),
('abuse','chodu','hindi'),
('abuse','chomu','hindi'),
('abuse','chootiya','hindi'),
('abuse','chuda','bengali'),
('abuse','chut ke baal','hindi'),
('abuse','chutia','hindi'),
('abuse','chutiya','gujarati'),
('abuse','chutiya','hindi'),
('abuse','chutiyapa','hindi'),
('abuse','chutiye','hindi'),
('abuse','chutya','marathi'),
('abuse','cocksucker','english'),
('abuse','dalla','hindi'),
('abuse','dalla','urdu'),
('abuse','dalle','punjabi'),
('abuse','dallya','punjabi'),
('abuse','dhakkan','hindi'),
('abuse','dick','english'),
('abuse','dickhead','english'),
('abuse','dipshit','english'),
('abuse','dongamunda','telugu'),
('abuse','douche','english'),
('abuse','douchebag','english'),
('abuse','dukkar','marathi'),
('abuse','dumbass','english'),
('abuse','erri puka','telugu'),
('abuse','fuck','english'),
('abuse','fuck off','english'),
('abuse','fuck you','english'),
('abuse','fucked','english'),
('abuse','fucker','english'),
('abuse','fucking','english'),
('abuse','fuddu','punjabi'),
('abuse','gaand','hindi'),
('abuse','gaand mara','hindi'),
('abuse','gaandu','bengali'),
('abuse','gaandu','hindi'),
('abuse','gadha','hindi'),
('abuse','gand','hindi'),
('abuse','gand mara','hindi'),
('abuse','gand phat','hindi'),
('abuse','gando','gujarati'),
('abuse','gandoo','punjabi'),
('abuse','gandu','bengali'),
('abuse','gandu','gujarati'),
('abuse','gandu','hindi'),
('abuse','gandu','kannada'),
('abuse','gandu','marathi'),
('abuse','ghanta','hindi'),
('abuse','ghatiya','hindi'),
('abuse','ghelo','gujarati'),
('abuse','gote','hindi'),
('abuse','gtfo','english'),
('abuse','gudda','telugu'),
('abuse','haraami','punjabi'),
('abuse','harami','gujarati'),
('abuse','haramjada','bengali'),
('abuse','haramjadi','bengali'),
('abuse','haramkhor','hindi'),
('abuse','haramkhor','marathi'),
('abuse','haramzada','urdu'),
('abuse','hijda','hindi'),
('abuse','hijra','hindi'),
('abuse','jackass','english'),
('abuse','jhaant ke baal','hindi'),
('abuse','jhant','hindi'),
('abuse','jhatu','hindi'),
('abuse','kameena','hindi'),
('abuse','kamina','hindi'),
('abuse','kamine','hindi'),
('abuse','kaminey','hindi'),
('abuse','kanjar','punjabi'),
('abuse','kanjar','urdu'),
('abuse','kanjri','punjabi'),
('abuse','kazhutha','malayalam'),
('abuse','khota','punjabi'),
('abuse','khotey','punjabi'),
('abuse','khotey','urdu'),
('abuse','kukka','telugu'),
('abuse','kutro','gujarati'),
('abuse','kutrya','marathi'),
('abuse','kutta','hindi'),
('abuse','kutta','punjabi'),
('abuse','kutta','urdu'),
('abuse','kuttar bachcha','bengali'),
('abuse','kutte','hindi'),
('abuse','kutti','punjabi'),
('abuse','lafangi','telugu'),
('abuse','lannti','punjabi'),
('abuse','lanti','punjabi'),
('abuse','laude','hindi'),
('abuse','lavde','hindi'),
('abuse','lavdu','hindi'),
('abuse','lavdya','marathi'),
('abuse','loafer','kannada'),
('abuse','lode','hindi'),
('abuse','lodu','hindi'),
('abuse','lodu lalit','hindi'),
('abuse','loosu','tamil'),
('abuse','lulli','hindi'),
('abuse','mairu','malayalam'),
('abuse','mayir','tamil'),
('abuse','mayiru','tamil'),
('abuse','mc','hindi'),
('abuse','meetha','hindi'),
('abuse','mkb','hindi'),
('abuse','mkc','hindi'),
('abuse','motherfuckin','english'),
('abuse','myre','malayalam'),
('abuse','nalayak','hindi'),
('abuse','neech','hindi'),
('abuse','pagla choda','bengali'),
('abuse','phuddu','punjabi'),
('abuse','piece of shit','english'),
('abuse','poda','tamil'),
('abuse','poda patti','malayalam'),
('abuse','podi','tamil'),
('abuse','porukki','tamil'),
('abuse','prick','english'),
('abuse','saala','hindi'),
('abuse','saali','hindi'),
('abuse','sala kutta','hindi'),
('abuse','sappa','tamil'),
('abuse','scumbag','english'),
('abuse','shaala','bengali'),
('abuse','shala','bengali'),
('abuse','shit','english'),
('abuse','shuor','bengali'),
('abuse','shuorer','bengali'),
('abuse','shut the fuck up','english'),
('abuse','singri','kannada'),
('abuse','son of bitch','english'),
('abuse','stfu','english'),
('abuse','suar','hindi'),
('abuse','tatte','hindi'),
('abuse','tatti','hindi'),
('abuse','teri gand','hindi'),
('abuse','thendi','malayalam'),
('abuse','tmkb','hindi'),
('abuse','tmkc','hindi'),
('abuse','twat','english'),
('abuse','ullu ka patha','hindi'),
('abuse','vailla','punjabi'),
('abuse','vedhava','telugu'),
('abuse','wanker','english'),
('abuse','wtf','english'),
('abuse','zaleel','urdu'),
('allow','abc','english'),
('allow','analysis','english'),
('allow','assassin','english'),
('allow','assist','english'),
('allow','assume','english'),
('allow','bass','english'),
('allow','bca','english'),
('allow','bcci','english'),
('allow','bcom','english'),
('allow','bcs','english'),
('allow','bhagwan','hindi'),
('allow','bitcoin','english'),

('allow','chutney','hindi'),
('allow','class','english'),
('allow','classic','english'),
('allow','cocktail','english'),
('allow','cumulative','english'),
('allow','dickens','english'),
('allow','document','english'),
('allow','drape','english'),
('allow','gandhi','hindi'),
('allow','gandhinagar','hindi'),
('allow','glass','english'),
('allow','grape','english'),
('allow','grass','english'),
('allow','hello','english'),
('allow','kuttappan','hindi'),
('allow','kutub','hindi'),
('allow','landing','hindi'),
('allow','lauki','hindi'),
('allow','london','hindi'),
('allow','mass','english'),
('allow','mca','english'),
('allow','mcdonalds','english'),
('allow','mcom','english'),
('allow','mcq','english'),
('allow','mcu','english'),
('allow','pass','english'),
('allow','passion','english'),
('allow','pussycat','english'),
('allow','saal','hindi'),
('allow','salaam','hindi'),
('allow','salad','hindi'),
('allow','salary','hindi'),
('allow','scunthorpe','english'),
('allow','shell','english'),
('allow','shitake','english'),
('allow','therapist','english'),
('allow','title','english'),
('mild','arivu kettavan','tamil'),
('mild','bajey','bengali'),
('mild','bakwaas','hindi'),
('mild','bakwas','hindi'),
('mild','bakwas na kar','punjabi'),
('mild','bawla','hindi'),
('mild','bewakoof','hindi'),
('mild','bewarse','telugu'),
('mild','bewkoof','hindi'),
('mild','bhaad mein ja','hindi'),
('mild','bhad me ja','hindi'),
('mild','bhag yaha se','hindi'),
('mild','boka','bengali'),
('mild','bokachoda na','bengali'),
('mild','chindi','hindi'),
('mild','chirkut','hindi'),
('mild','chomu','hindi'),
('mild','chup kar','hindi'),
('mild','chup kar','punjabi'),
('mild','chup kor','bengali'),
('mild','crap','english'),
('mild','dammit','english'),
('mild','damn','english'),
('mild','dimag kharab','hindi'),
('mild','dumb','english'),
('mild','erripuka','telugu'),
('mild','faltu','bengali'),
('mild','faltu','hindi'),
('mild','gadha','bengali'),
('mild','gadha','hindi'),
('mild','ganda','punjabi'),
('mild','ganjuti','bengali'),
('mild','ganwaar','hindi'),
('mild','hangla','bengali'),
('mild','idiot','english'),
('mild','jahil','hindi'),
('mild','jerk','english'),
('mild','kamchor','hindi'),
('mild','khotya','punjabi'),
('mild','lallu','hindi'),
('mild','loosu','tamil'),
('mild','loser','english'),
('mild','lusu','tamil'),
('mild','mental','tamil'),
('mild','moron','english'),
('mild','muttal','tamil'),
('mild','nalayak','hindi'),
('mild','nikamma','hindi'),
('mild','nikamma','punjabi'),
('mild','pagal','hindi'),
('mild','pagal','punjabi'),
('mild','pagol','bengali'),
('mild','pathetic','english'),
('mild','pichodu','telugu'),
('mild','saala','hindi'),
('mild','sala','hindi'),
('mild','screw you','english'),
('mild','shut up','english'),
('mild','stupid','english'),
('mild','sucker','english'),
('mild','tharki','hindi'),
('mild','ullu','hindi'),
('mild','ullu da patha','punjabi'),
('mild','vehla','punjabi'),
('provoking','1v1 me irl','english'),
('provoking','aaja lad','hindi'),
('provoking','address bhej','hindi'),
('provoking','admin bula','hindi'),
('provoking','aukaat mein reh','hindi'),
('provoking','aukat','hindi'),
('provoking','aukat ch reh','punjabi'),
('provoking','aukat dikha','hindi'),
('provoking','bahar aa','hindi'),
('provoking','bahar mil','hindi'),
('provoking','bahar mil tu','punjabi'),
('provoking','bairer ay','bengali'),
('provoking','ban karwa','hindi'),
('provoking','beat you up','english'),
('provoking','chak lavange','punjabi'),
('provoking','come outside','english'),
('provoking','coming for you','english'),
('provoking','ddos','hindi'),
('provoking','ddos you','english'),
('provoking','dekh lunga','hindi'),
('provoking','dekhe nebo','bengali'),
('provoking','dox','hindi'),
('provoking','dox you','english'),
('provoking','fight me','english'),
('provoking','ghar aa ke','hindi'),
('provoking','ghar aa ke maarange','punjabi'),
('provoking','ghar ka pata','hindi'),
('provoking','hack kar dunga','hindi'),
('provoking','haddi tod','hindi'),
('provoking','himmat hai to','hindi'),
('provoking','i know where you live','english'),
('provoking','i will find you','english'),
('provoking','i will kill you','english'),
('provoking','i''ll hack you','english'),
('provoking','ill find you','english'),
('provoking','ill kill you','english'),
('provoking','ip grab','english'),
('provoking','ip nikal','hindi'),
('provoking','jaan se maar','hindi'),
('provoking','khoon pi jaunga','hindi'),
('provoking','khun kore debo','bengali'),
('provoking','kill you','english'),
('provoking','ladega','hindi'),
('provoking','lagau kya','hindi'),
('provoking','maar daalunga','hindi'),
('provoking','maar dunga','hindi'),
('provoking','mar dunga','punjabi'),
('provoking','mere felbo','bengali'),
('provoking','muh tod','hindi'),
('provoking','report karunga','hindi'),
('provoking','swat you','english'),
('provoking','tera kaam tamaam','hindi'),
('provoking','teri aukat','hindi'),
('provoking','thappad marunga','hindi'),
('provoking','thappor marbo','bengali'),
('provoking','thok dunga','punjabi'),
('provoking','tod dunga','hindi'),
('provoking','tujhe dekh lunga','hindi'),
('provoking','watch your back','english'),
('provoking','you are dead','english'),
('provoking','you''re dead','english'),
('severe','aai la','marathi'),
('severe','aai zavadya','marathi'),
('severe','aaichya gavat','marathi'),
('severe','aaighalya','marathi'),
('severe','baap pe mat ja','hindi'),
('severe','bahanchod','hindi'),
('severe','bap ka maal','hindi'),
('severe','bastard','english'),
('severe','behen ke laude','hindi'),
('severe','behen ke lode','hindi'),
('severe','behenchod','hindi'),
('severe','ben na lodo','gujarati'),
('severe','beshyar chele','bengali'),
('severe','bhen chod','punjabi'),
('severe','bhen di','punjabi'),
('severe','bhen yaawan','punjabi'),
('severe','bhenchod','hindi'),
('severe','bhopadike','hindi'),
('severe','bhosadike','hindi'),
('severe','bhosadpappu','hindi'),
('severe','bhosdi ke','hindi'),
('severe','bhosdichya','marathi'),
('severe','bhosdike','hindi'),
('severe','bhosdiwale','hindi'),
('severe','bhosdk','hindi'),
('severe','boli maga','kannada'),
('severe','bolimaga','kannada'),
('severe','bonchod','bengali'),
('severe','chutmarike','hindi'),
('severe','cunt','english'),
('severe','dalle ki aulad','urdu'),
('severe','dengey ra','telugu'),
('severe','dengu ra','telugu'),
('severe','fag','english'),
('severe','faggot','english'),
('severe','fuck your mom','english'),
('severe','fuck your mother','english'),
('severe','fuck your sister','english'),
('severe','gandu ki aulad','hindi'),
('severe','go die','english'),
('severe','harami','hindi'),
('severe','haramjada','bengali'),
('severe','haramkhor','hindi'),
('severe','haramzada','hindi'),
('severe','haramzade','urdu'),
('severe','haramzadi','hindi'),
('severe','kanjari ki aulad','urdu'),
('severe','khankir chele','bengali'),
('severe','khankir pola','bengali'),
('severe','khotey di aulad','punjabi'),
('severe','kill yourself','english'),
('severe','koothi mavane','tamil'),
('severe','kundi mone','malayalam'),
('severe','kutte ki aulad','hindi'),
('severe','kutti de puttar','punjabi'),
('severe','kuttiya da puttar','punjabi'),
('severe','kys','english'),
('severe','lanja kodaka','telugu'),
('severe','lann teri maa','punjabi'),
('severe','maa chod','hindi'),
('severe','maa chod','punjabi'),
('severe','maa chuda','hindi'),
('severe','maa da','punjabi'),
('severe','maa di','punjabi'),
('severe','maa ke laude','hindi'),
('severe','maa ke lode','hindi'),
('severe','maa ki chut','hindi'),
('severe','maa na','gujarati'),
('severe','maa yaawan','punjabi'),
('severe','maachod','bengali'),
('severe','maadarchod','gujarati'),
('severe','madarchod','hindi'),
('severe','madarjaat','hindi'),
('severe','maderchod','hindi'),
('severe','mother fucker','english'),
('severe','motherfucker','english'),
('severe','motherfucking','english'),
('severe','nee akka','telugu'),
('severe','nee amma','telugu'),
('severe','ni amma','telugu'),
('severe','ni yamma','telugu'),
('severe','nigga','english'),
('severe','nigger','english'),
('severe','ninamma','kannada'),
('severe','ninn akka','kannada'),
('severe','ninna amma','kannada'),
('severe','ninte achan','malayalam'),
('severe','ninte amma','malayalam'),
('severe','ommala','tamil'),
('severe','otha','tamil'),
('severe','pehnchod','punjabi'),
('severe','pen chod','punjabi'),
('severe','penchod','punjabi'),
('severe','poori mone','malayalam'),
('severe','pundachi mone','malayalam'),
('severe','pundamavane','tamil'),
('severe','randi ka bacha','hindi'),
('severe','randi ki aulad','hindi'),
('severe','retard','english'),
('severe','shuar er bachcha','bengali'),
('severe','shuorer bachcha','bengali'),
('severe','son of a bitch','english'),
('severe','sonofabitch','english'),
('severe','soole magane','kannada'),
('severe','suar ki aulad','hindi'),
('severe','taari maa','gujarati'),
('severe','tari ben ne','gujarati'),
('severe','tari maa ne','gujarati'),
('severe','tera baap','hindi'),
('severe','tere baap ki','hindi'),
('severe','teri ammi','urdu'),
('severe','teri behen','urdu'),
('severe','teri behen ki','hindi'),
('severe','teri behen ko','hindi'),
('severe','teri bhen di','punjabi'),
('severe','teri maa di','punjabi'),
('severe','teri maa ka','hindi'),
('severe','teri maa ki','hindi'),
('severe','teri maa ki','urdu'),
('severe','teri maa ko','hindi'),
('severe','teri maa nu','punjabi'),
('severe','teri mummy','hindi'),
('severe','teri mummy ki','hindi'),
('severe','teri mummy ko','hindi'),
('severe','teri pen nu','punjabi'),
('severe','thayoli','malayalam'),
('severe','thevidiya mavane','tamil'),
('severe','thevidiya paiya','tamil'),
('severe','tor baap','bengali'),
('severe','tor bon ke','bengali'),
('severe','tor maa','bengali'),
('severe','tor maa chudi','bengali'),
('severe','tor maa ke','bengali'),
('severe','tor maa ke chudi','bengali'),
('severe','tujha baap','marathi'),
('severe','tujhya aaichi','marathi'),
('severe','tuzi aai','marathi'),
('severe','un aatha','tamil'),
('severe','un amma','tamil'),
('severe','yo mama','english'),
('severe','your mom','english'),
('sexual','aai zavli','marathi'),
('sexual','aaizavadya','marathi'),
('sexual','beshya','bengali'),
('sexual','bessha','bengali'),
('sexual','bevarsi','kannada'),
('sexual','bhosda','hindi'),
('sexual','bhosdi','gujarati'),
('sexual','bhosdya','marathi'),
('sexual','bhosrina','gujarati'),
('sexual','bistar pe aa','hindi'),
('sexual','blowjob','english'),
('sexual','boobe','hindi'),
('sexual','boobs','english'),
('sexual','camgirl','english'),
('sexual','chhinal','hindi'),
('sexual','chinal','hindi'),
('sexual','chod deyan','punjabi'),
('sexual','chod dunga','hindi'),
('sexual','chodbo','bengali'),
('sexual','chodu','gujarati'),
('sexual','chodunga','hindi'),
('sexual','chodya','gujarati'),
('sexual','choos le','hindi'),
('sexual','choot','hindi'),
('sexual','chudai','hindi'),
('sexual','chudakkad','hindi'),
('sexual','chudasi','hindi'),
('sexual','chudi','bengali'),
('sexual','chudir bhai','bengali'),
('sexual','chudwa','hindi'),
('sexual','chut','hindi'),
('sexual','chut mein','hindi'),
('sexual','cum','english'),
('sexual','cumshot','english'),
('sexual','dalla','urdu'),
('sexual','deepthroat','english'),
('sexual','dengey','telugu'),
('sexual','dengu','telugu'),
('sexual','dengutha','telugu'),
('sexual','dhon chosh','bengali'),
('sexual','dick pic','english'),
('sexual','doodh dikha','hindi'),
('sexual','fuddi','hindi'),
('sexual','fuddu','punjabi'),
('sexual','fudi','punjabi'),
('sexual','gaand mar','hindi'),
('sexual','gaand marunga','hindi'),
('sexual','gand mein','hindi'),
('sexual','gando','gujarati'),
('sexual','gashti','urdu'),
('sexual','ghalu','marathi'),
('sexual','ghelchodiya','gujarati'),
('sexual','grope','english'),
('sexual','gud marani','bengali'),
('sexual','gudda','telugu'),
('sexual','gudmarani','bengali'),
('sexual','handjob','english'),
('sexual','hila','hindi'),
('sexual','hilana','hindi'),
('sexual','hoe','english'),
('sexual','horny','english'),
('sexual','i will rape you','english'),
('sexual','item hai','hindi'),
('sexual','jhaant','hindi'),
('sexual','jhaatu','hindi'),
('sexual','kanjar','urdu'),
('sexual','kanjari','urdu'),
('sexual','khankir chele','bengali'),
('sexual','khotey da lan','punjabi'),
('sexual','koothi','tamil'),
('sexual','koothichi','malayalam'),
('sexual','kundi','malayalam'),
('sexual','kunna','malayalam'),
('sexual','kutiya','hindi'),
('sexual','lanja','telugu'),
('sexual','lanjakodaka','telugu'),
('sexual','lann chak','punjabi'),
('sexual','lauda','hindi'),
('sexual','lavda','marathi'),
('sexual','lavdya','marathi'),
('sexual','lawda','hindi'),
('sexual','lele mera','hindi'),
('sexual','lets have sex','english'),
('sexual','loda','gujarati'),
('sexual','loda','hindi'),
('sexual','lodo','gujarati'),
('sexual','lun choos','urdu'),
('sexual','lund','hindi'),
('sexual','lund choos','hindi'),
('sexual','maal hai','hindi'),
('sexual','mairu','malayalam'),
('sexual','mera choos','hindi'),
('sexual','milf','english'),
('sexual','modda','telugu'),
('sexual','molest','english'),
('sexual','molester','english'),
('sexual','muth','hindi'),
('sexual','muthi','hindi'),
('sexual','mutthal','hindi'),
('sexual','myre','malayalam'),
('sexual','nanga kar','hindi'),
('sexual','nangi','hindi'),
('sexual','nudes bhej','english'),
('sexual','ommala','tamil'),
('sexual','oombu','tamil'),
('sexual','oombudhu','tamil'),
('sexual','ootha','tamil'),
('sexual','otha','tamil'),
('sexual','pedo','english'),
('sexual','pedophile','english'),
('sexual','phuddi','hindi'),
('sexual','phuddi','urdu'),
('sexual','phuddi de','punjabi'),
('sexual','phuddu','punjabi'),
('sexual','phudi','punjabi'),
('sexual','poori mone','malayalam'),
('sexual','pooru','malayalam'),
('sexual','porn','english'),
('sexual','pornstar','english'),
('sexual','puku','telugu'),
('sexual','punda','tamil'),
('sexual','pundai','tamil'),
('sexual','pussy','english'),
('sexual','raand','hindi'),
('sexual','raat ko aa','hindi'),
('sexual','rand','hindi'),
('sexual','randi','hindi'),
('sexual','randichya','marathi'),
('sexual','randwa','hindi'),
('sexual','rape','english'),
('sexual','raping','english'),
('sexual','rapist','english'),
('sexual','send nudes','english'),
('sexual','sex with you','english'),
('sexual','sexy body','english'),
('sexual','sexy maal','hindi'),
('sexual','show boobs','english'),
('sexual','show tits','english'),
('sexual','show your boobs','english'),
('sexual','sleep with me','english'),
('sexual','slut','english'),
('sexual','soole','kannada'),
('sexual','strip for me','english'),
('sexual','suck my cock','english'),
('sexual','suck my dick','english'),
('sexual','sunni','tamil'),
('sexual','taari maa ne','gujarati'),
('sexual','tatte','hindi'),
('sexual','tatti kha','hindi'),
('sexual','teri chut','hindi'),
('sexual','teri phuddi','punjabi'),
('sexual','thayoli','malayalam'),
('sexual','thevdiya','tamil'),
('sexual','thevidiya','tamil'),
('sexual','thot','english'),
('sexual','thullu','kannada'),
('sexual','tits','english'),
('sexual','touch you there','english'),
('sexual','tujhe chodunga','hindi'),
('sexual','tullu','kannada'),
('sexual','tunne','kannada'),
('sexual','whore','english'),
('sexual','yaawan','punjabi'),
('sexual','yawaan','punjabi'),
('sexual','zavadya','marathi'),
('sexual','zavnya','marathi'),
('sexual','zhavadya','marathi')
on conflict (category,word) do nothing;

alter table public.bot_settings add column text_channel_ids text[] not null default '{}', add column text_all_channels boolean not null default false;

-- Punishment appeals upgrade
ALTER TABLE public.bot_settings ADD COLUMN IF NOT EXISTS alert_role_ids text[] NOT NULL DEFAULT '{}';
UPDATE public.bot_settings SET alert_role_ids = ARRAY[alert_role_id] WHERE cardinality(alert_role_ids) = 0 AND alert_role_id <> '';
ALTER TABLE public.infractions ADD COLUMN IF NOT EXISTS guild_id text NOT NULL DEFAULT '', ADD COLUMN IF NOT EXISTS ai_verdict text NOT NULL DEFAULT '', ADD COLUMN IF NOT EXISTS ai_reason text NOT NULL DEFAULT '';
CREATE TABLE public.punishment_appeals (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 infraction_id uuid NOT NULL UNIQUE REFERENCES public.infractions(id),
 discord_user_id text NOT NULL,
 explanation text NOT NULL,
 status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','processing','approved','rejected')),
 moderator_id text NOT NULL DEFAULT '', moderator_name text NOT NULL DEFAULT '',
 resolution text NOT NULL DEFAULT '', review_message_id text NOT NULL DEFAULT '', review_channel_id text NOT NULL DEFAULT '',
 created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz
);
GRANT SELECT ON public.punishment_appeals TO authenticated;
GRANT ALL ON public.punishment_appeals TO service_role;
ALTER TABLE public.punishment_appeals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "admins read appeals" ON public.punishment_appeals FOR SELECT TO authenticated USING (public.has_role(auth.uid(),'admin'));
CREATE INDEX punishment_appeals_pending_idx ON public.punishment_appeals(status, created_at DESC);
CREATE OR REPLACE FUNCTION public.finish_punishment_appeal(_id uuid, _moderator_id text, _approved boolean, _resolution text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE target uuid;
BEGIN
 UPDATE public.punishment_appeals SET status = CASE WHEN _approved THEN 'approved' ELSE 'rejected' END, resolution = _resolution, resolved_at = now() WHERE id = _id AND status = 'processing' AND moderator_id = _moderator_id RETURNING infraction_id INTO target;
 IF target IS NULL THEN RAISE EXCEPTION 'Appeal is not claimed by this moderator'; END IF;
 IF _approved THEN UPDATE public.infractions SET cleared = true WHERE id = target; END IF;
END $$;
REVOKE ALL ON FUNCTION public.finish_punishment_appeal(uuid,text,boolean,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.finish_punishment_appeal(uuid,text,boolean,text) TO service_role;
NOTIFY pgrst, 'reload schema';

-- Punishment appeals upgrade
ALTER TABLE public.infractions ADD COLUMN IF NOT EXISTS punishment_expires_at timestamptz;
ALTER TABLE public.punishment_appeals ADD COLUMN IF NOT EXISTS claim_token uuid, ADD COLUMN IF NOT EXISTS claimed_at timestamptz;
CREATE OR REPLACE FUNCTION public.finish_punishment_appeal(_id uuid, _moderator_id text, _approved boolean, _resolution text, _claim_token uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE target uuid;
BEGIN
 UPDATE public.punishment_appeals SET status = CASE WHEN _approved THEN 'approved' ELSE 'rejected' END, resolution = _resolution, resolved_at = now() WHERE id = _id AND status = 'processing' AND moderator_id = _moderator_id AND claim_token = _claim_token RETURNING infraction_id INTO target;
 IF target IS NULL THEN RAISE EXCEPTION 'Appeal claim is no longer valid'; END IF;
 IF _approved THEN UPDATE public.infractions SET cleared = true WHERE id = target; END IF;
END $$;
REVOKE ALL ON FUNCTION public.finish_punishment_appeal(uuid,text,boolean,text,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.finish_punishment_appeal(uuid,text,boolean,text,uuid) TO service_role;
REVOKE EXECUTE ON FUNCTION public.finish_punishment_appeal(uuid,text,boolean,text) FROM service_role;
NOTIFY pgrst, 'reload schema';
-- Punishment access repair
GRANT ALL ON public.bot_settings, public.infractions, public.ai_decision_logs, public.punishment_appeals TO service_role;
NOTIFY pgrst, 'reload schema';
