/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiLogsRouteImport } from './routes/ai-logs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as WordsRouteImport } from './routes/words'
import { Route as ApiPublicBotActionRouteImport } from './routes/api/public/bot.$action'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLogsRoute = AiLogsRouteImport.update({
  id: '/ai-logs',
  path: '/ai-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsRoute = WordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotActionRoute = ApiPublicBotActionRouteImport.update({
  id: '/api/public/bot/$action',
  path: '/api/public/bot/$action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-logs': typeof AiLogsRoute
  '/auth': typeof AuthRoute
  '/channels': typeof ChannelsRoute
  '/history': typeof HistoryRoute
  '/rules': typeof RulesRoute
  '/words': typeof WordsRoute
  '/api/public/bot/$action': typeof ApiPublicBotActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-logs': typeof AiLogsRoute
  '/auth': typeof AuthRoute
  '/channels': typeof ChannelsRoute
  '/history': typeof HistoryRoute
  '/rules': typeof RulesRoute
  '/words': typeof WordsRoute
  '/api/public/bot/$action': typeof ApiPublicBotActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-logs': typeof AiLogsRoute
  '/auth': typeof AuthRoute
  '/channels': typeof ChannelsRoute
  '/history': typeof HistoryRoute
  '/rules': typeof RulesRoute
  '/words': typeof WordsRoute
  '/api/public/bot/$action': typeof ApiPublicBotActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-logs'
    | '/auth'
    | '/channels'
    | '/history'
    | '/rules'
    | '/words'
    | '/api/public/bot/$action'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-logs'
    | '/auth'
    | '/channels'
    | '/history'
    | '/rules'
    | '/words'
    | '/api/public/bot/$action'
  id:
    | '__root__'
    | '/'
    | '/ai-logs'
    | '/auth'
    | '/channels'
    | '/history'
    | '/rules'
    | '/words'
    | '/api/public/bot/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiLogsRoute: typeof AiLogsRoute
  AuthRoute: typeof AuthRoute
  ChannelsRoute: typeof ChannelsRoute
  HistoryRoute: typeof HistoryRoute
  RulesRoute: typeof RulesRoute
  WordsRoute: typeof WordsRoute
  ApiPublicBotActionRoute: typeof ApiPublicBotActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-logs': {
      id: '/ai-logs'
      path: '/ai-logs'
      fullPath: '/ai-logs'
      preLoaderRoute: typeof AiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words': {
      id: '/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/$action': {
      id: '/api/public/bot/$action'
      path: '/api/public/bot/$action'
      fullPath: '/api/public/bot/$action'
      preLoaderRoute: typeof ApiPublicBotActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiLogsRoute: AiLogsRoute,
  AuthRoute: AuthRoute,
  ChannelsRoute: ChannelsRoute,
  HistoryRoute: HistoryRoute,
  RulesRoute: RulesRoute,
  WordsRoute: WordsRoute,
  ApiPublicBotActionRoute: ApiPublicBotActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
